### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by 0xmad** [errmac-v/cargo-build-dependencies#11]
### Features to implement
- [ ] --help for cli
- [ ] --dev key for building dev dependencies
- [ ] Support building multiple workspaces
